[config]
schemaVersion = "0.0.1"

[package]
namespace = "TritonSupreme"
name = "ExtendedRadio"
versionNumber = "0.1.0"
description = "A mod to improve the game's radio."
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
# AuthorName-PackageName = "0.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" "audio"]