[config]
schemaVersion = "0.0.1"

[package]
namespace = "TritonSupreme"
name = "ExtendedRadio"
versionNumber = "0.2.0"
description = "This mod aims to add features and improve existing ones for the game's radio player. MAKE A BACKUP OF YOUR CUSTOM RADIO BEFORE UPDATE IF YOU USE THE THUNDERSTORE MOD MANAGER"
websiteUrl = "https://github.com/AlphaGaming7780/ExtendedRadio"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
# AuthorName-PackageName = "0.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods", "audio"]